print("Let's play Mad Libs for Homework 1")
print('Type one word responses to the following: ', '\n')
name = input('proper_name ==> ').strip()
print(name)
a1 = input('adjective ==> ').strip()
print(a1)
n1 = input('noun ==> ').strip()
print(n1)
v1 = input('verb ==> ').strip()
print(v1)
v2 = input('verb ==> ').strip()
print(v2)
n2 = input('noun ==> ').strip()
print(n2)
e1 = input('emotion ==> ').strip()
print(e1)
v3 = input('verb ==> ').strip()
print(v3)
n3 = input('noun ==> ').strip()
print(n3)
s1 = input('season ==> ').strip()
print(s1)
a2 = input('adjective ==> ').strip()
print(a2)
e2 = input('emotion ==> ').strip()
print(e2)
t1 = input('team-name ==> ').strip()
print(t1)
n4 = input('noun ==> ').strip()
print(n4)
a3 = input('adjective ==> ').strip()
print(a3, '\n')

print('Here is your Mad Lib...\n')
print("Good morning ", name, "!",'\n', sep = '')
print('\t', "This will be a/an ", a1, " ", n1, "! Are you ", v1," forward to it?", sep = '')
print('\t', "You will ",v2," a lot of ",n2," and feel ",e1," when you do.", sep = '')
print('\t', "If you do not, you will ",v3," this ",n3,".", '\n', sep = '')
print('\t', "This ",s1," was ",a2,". Were you ",e2," when ",t1," won", "\n" ,"\tthe ",n4,"?\n", sep = '')
print("\tHave a/an ",a3," day!", sep = '')

